### PR TITLE
Fix PyPi publishing

### PR DESCRIPTION
**Pull request by Hovercross**
Fix the configurations so that this can be properly published to PyPi

- Update the release tag reader so that the tag has to start with "v" for automated publishing to work
- Update the project name to the proper json-position-mapper

### CODE REVIEW

**Review by DavidMertz — CHANGES_REQUESTED** [review]
We should be at least version 0.0.1 (but probably just 0.1.0).

**Comment by Hovercross** [comment]
> We should be at least version 0.0.1 (but probably just 0.1.0).

That actually happens automatically in the publishing workflow. When you create a Github release you give it a tag such as `v0.1.0`, and there is a step in the release process that versions the library before uploading to PyPi

**Review by forrestgrant — APPROVED** [review]
👍

**Review by jack-collier-prepmd — APPROVED** [review]

**Review by DavidMertz — APPROVED** [review]
Versioning handled in pipeline

**Pull request merged**
